Repository aquarist-labs/s3gw-charts, pull requests merged in 2022-11, with the labels that each got.

#58 Add wildcard host to tls section.
  CHANGELOG.md
  charts/s3gw/templates/ingress-traefik.yaml
Labels: enhancement

#60 Bump chart version to 0.8.0.
  charts/s3gw/Chart.yaml
Labels: enhancement

#61 Update changelog for v0.8.0.
  CHANGELOG.md
Labels: documentation

#56 Add multi domain configuration
  CHANGELOG.md
  charts/s3gw/questions.yaml
  charts/s3gw/templates/configmap.yaml
  charts/s3gw/templates/deployment.yaml
  charts/s3gw/templates/ingress-secret.yaml
  charts/s3gw/templates/ingress-traefik.yaml
  charts/s3gw/templates/service.yaml
  charts/s3gw/templates/tests/smoke-bucket-create.yaml
  charts/s3gw/values.yaml
Labels: kind/enhancement
